title: abrhoda.github.io
description: Building neat software.
author: Alexander Rhoda
github: https://github.com/abrhoda
about: Exploring concepts in software.
# google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

social:
    - icon: fa-github
      link: "https://github.com/abrhoda"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/alexander-rhoda"

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://abrhoda.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
permalink: "/:slug/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
